version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: portal_db
    environment:
      POSTGRES_DB: portal_empresas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portal_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portal_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: portal_empresas
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - portal_network
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portal_frontend
    ports:
      - "8080:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - portal_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  portal_network:
    driver: bridge
